---@class my.appearance.btop
local M = {}
local fs = require('my.utils.fs')

local config_dir = vim.fs.joinpath(
  vim.env.XDG_CONFIG_HOME or vim.fs.joinpath(vim.env.HOME, '.config'),
  'btop'
)
local config_path = vim.fs.joinpath(config_dir, 'btop.conf')
local theme_path = vim.fs.joinpath(config_dir, 'themes', 'avra-nvim.theme')
local state_path = vim.fs.joinpath(vim.fn.stdpath('state'), 'btop-sync.json')
local theme_name = 'avra-nvim'
local marker = '# Generated by Avra.nvim; edit your Neovim theme instead.'
local warned ---@type string?

---@param message string
---@return nil
local function warn(message)
  if warned ~= message then
    warned = message
    vim.notify('BTOP theme: ' .. message, vim.log.levels.WARN)
  end
end

---@param path string
---@param content string
---@return boolean
local function write(path, content)
  if fs.read_file(path) == content then
    return true
  end
  local ok = pcall(vim.fn.mkdir, vim.fs.dirname(path), 'p')
  if not ok then
    return false
  end
  local temporary = path .. '.avra-' .. vim.fn.getpid() .. '.tmp'
  local stat = vim.uv.fs_stat(path)
  local fd = vim.uv.fs_open(temporary, 'w', stat and stat.mode or 384)
  if not fd then
    return false
  end
  local written = vim.uv.fs_write(fd, content, 0)
  vim.uv.fs_close(fd)
  if written ~= #content or not vim.uv.fs_rename(temporary, path) then
    vim.uv.fs_unlink(temporary)
    return false
  end
  return true
end

---@param content string
---@param replacement? string
---@return string?, string?
local function replace_theme(content, replacement)
  local offset = 1
  while offset <= #content do
    local newline = content:find('\n', offset, true) or #content + 1
    local line = content:sub(offset, newline - 1)
    local prefix, current, suffix =
      line:match('^([ \t]*color_theme[ \t]*=[ \t]*)"([^"\n]*)"(.*)$')
    if prefix then
      if not replacement then
        return content, current
      end
      local updated = prefix .. '"' .. replacement .. '"' .. suffix
      return content:sub(1, offset - 1) .. updated .. content:sub(newline),
        current
    end
    offset = newline + 1
  end
  return nil, nil
end

---@return string?
local function original_theme()
  local content = fs.read_file(state_path)
  if not content then
    return nil
  end
  local ok, state = pcall(vim.json.decode, content)
  if
    ok
    and type(state) == 'table'
    and state.config_path == config_path
    and type(state.original_theme) == 'string'
  then
    return state.original_theme
  end
  warn('invalid recovery state: ' .. state_path)
  return nil
end

---@return boolean
function M.available()
  if vim.fn.executable('btop') ~= 1 or not vim.uv.fs_stat(config_path) then
    return false
  end
  for _, ui in ipairs(vim.api.nvim_list_uis()) do
    if ui.stdout_tty then
      return true
    end
  end
  return false
end

---@param palette my.appearance.ghostty.palette
---@param transparent boolean
---@return string
function M.compose(palette, transparent)
  local colors = palette.colors
  local values = {
    main_bg = transparent and '' or palette.background,
    main_fg = palette.foreground,
    title = palette.foreground,
    hi_fg = colors[5],
    selected_bg = palette.selection_background,
    selected_fg = palette.selection_foreground,
    inactive_fg = colors[9],
    proc_misc = colors[7],
    cpu_box = colors[5],
    mem_box = colors[3],
    net_box = colors[7],
    proc_box = colors[6],
    div_line = colors[9],
    temp_start = colors[3],
    temp_mid = colors[4],
    temp_end = colors[2],
    cpu_start = colors[3],
    cpu_mid = colors[4],
    cpu_end = colors[2],
    free_start = colors[3],
    free_mid = colors[7],
    free_end = colors[5],
    cached_start = colors[5],
    cached_mid = colors[6],
    cached_end = colors[7],
    available_start = colors[3],
    available_mid = colors[7],
    available_end = colors[5],
    used_start = colors[4],
    used_mid = colors[2],
    used_end = colors[2],
    download_start = colors[5],
    download_mid = colors[7],
    download_end = colors[3],
    upload_start = colors[6],
    upload_mid = colors[4],
    upload_end = colors[2],
  }
  local lines = {} ---@type string[]
  local keys = vim.tbl_keys(values)
  table.sort(keys)
  for _, key in ipairs(keys) do
    lines[#lines + 1] = 'theme[' .. key .. ']="' .. values[key] .. '"'
  end
  local body = table.concat(lines, '\n') .. '\n'
  return marker .. ' sha256=' .. vim.fn.sha256(body) .. '\n' .. body
end

---@return nil
local function reload()
  local uid = vim.uv.getuid()
  if uid then
    -- btop reloads its config and theme on SIGUSR2. No process is normal.
    vim.system({ 'pkill', '-USR2', '-U', tostring(uid), '-x', 'btop' })
  end
end

---Update the generated theme and the single BTOP config setting.
---@param palette my.appearance.ghostty.palette
---@param transparent boolean
---@return boolean
function M.sync(palette, transparent)
  if not M.available() then
    return false
  end
  local config = fs.read_file(config_path)
  local _, current = replace_theme(config or '')
  if not current then
    warn('could not find color_theme in ' .. config_path)
    return false
  end
  local previous = original_theme()
  if fs.read_file(state_path) and not previous then
    return false
  end
  if current == theme_name and not previous then
    warn('color_theme is already avra-nvim, but recovery state is missing.')
    return false
  end
  if current ~= theme_name and previous and current ~= previous then
    warn('color_theme was changed outside Neovim; leaving it intact.')
    return false
  end
  local theme = M.compose(palette, transparent)
  local existing = fs.read_file(theme_path)
  if existing then
    local prefix = marker .. ' sha256='
    local newline = existing:find('\n', 1, true)
    local checksum = newline and existing:sub(#prefix + 1, newline - 1)
    local body = newline and existing:sub(newline + 1)
    if
      not vim.startswith(existing, prefix)
      or not checksum
      or not body
      or not checksum:match('^%x+$')
      or vim.fn.sha256(body) ~= checksum
    then
      warn('existing theme was edited; leaving it intact: ' .. theme_path)
      return false
    end
  end
  if not previous then
    local encoded = vim.json.encode({
      config_path = config_path,
      original_theme = current,
    })
    if not write(state_path, encoded) then
      warn('could not save the original color_theme.')
      return false
    end
  end
  local changed = existing ~= theme
  if changed and not write(theme_path, theme) then
    warn('could not write ' .. theme_path)
    return false
  end
  if current ~= theme_name then
    local updated = replace_theme(config, theme_name)
    if
      fs.read_file(config_path) ~= config or not write(config_path, updated)
    then
      warn('btop.conf changed or could not be written.')
      return false
    end
    changed = true
  end
  if changed then
    reload()
  end
  warned = nil
  return true
end

---Restore the previous BTOP theme when sync is disabled.
---@return nil
function M.reset()
  local previous = original_theme()
  if not previous then
    return
  end
  local config = fs.read_file(config_path)
  local _, current = replace_theme(config or '')
  if current == previous then
    vim.uv.fs_unlink(state_path)
    return
  end
  if current ~= theme_name then
    warn('color_theme was changed outside Neovim; leaving it intact.')
    return
  end
  local updated = replace_theme(config, previous)
  if not write(config_path, updated) then
    warn('could not restore the original color_theme.')
    return
  end
  vim.uv.fs_unlink(state_path)
  reload()
  warned = nil
end

return M
