---@class my.appearance.ghostty
local M = {}

---@class my.appearance.ghostty.palette
---@field foreground string
---@field background string
---@field cursor string
---@field selection_foreground string
---@field selection_background string
---@field colors string[] ANSI colors, indexed from 1

local esc = '\27'
local terminator = esc .. '\\'
local changed = false

---@param value string|integer|nil
---@return string?
local function color(value)
  if type(value) == 'number' and value >= 0 and value <= 0xffffff then
    return string.format('#%06x', value)
  end
  if type(value) == 'string' and value:match('^#%x%x%x%x%x%x$') then
    return value:lower()
  end
end

---@param name string
---@param attr 'fg'|'bg'
---@return string?
local function highlight_color(name, attr)
  return color(
    vim.api.nvim_get_hl(0, { name = name, link = false, create = false })[attr]
  )
end

---Use the colorscheme's palette, with syntax colors as a fallback.
---@param normal vim.api.keyset.get_hl_info
---@return my.appearance.ghostty.palette
function M.palette(normal)
  local dark = vim.o.background == 'dark'
  local foreground = color(normal.fg) or (dark and '#eeeeee' or '#222222')
  local background = color(normal.bg)
    or color(vim.g.terminal_color_0)
    or (dark and '#14161b' or '#ffffff')
  local fallback_groups = {
    'Normal',
    'DiagnosticError',
    'String',
    'DiagnosticWarn',
    'Function',
    'Statement',
    'Type',
    'Normal',
    'Comment',
    'DiagnosticError',
    'String',
    'DiagnosticWarn',
    'Function',
    'Statement',
    'Type',
    'Normal',
  }
  local colors = {} ---@type string[]
  for i = 0, 15 do
    colors[i + 1] = color(vim.g['terminal_color_' .. i])
      or (i == 0 and background)
      or highlight_color(fallback_groups[i + 1], 'fg')
      or foreground
  end
  return {
    foreground = foreground,
    background = background,
    cursor = highlight_color('Cursor', 'bg') or foreground,
    selection_foreground = highlight_color('Visual', 'fg') or foreground,
    selection_background = highlight_color('Visual', 'bg') or colors[9],
    colors = colors,
  }
end

---@param code integer
---@param value string?
---@return string
local function osc(code, value)
  return esc .. ']' .. code .. (value and ';' .. value or '') .. terminator
end

---Send control sequences only to an attached Ghostty or Herdr terminal UI.
---@return boolean
function M.available()
  if
    vim.env.TERM_PROGRAM ~= 'ghostty'
    and vim.env.TERM ~= 'xterm-ghostty'
    and not (vim.env.TMUX and vim.env.GHOSTTY_RESOURCES_DIR)
    and vim.env.HERDR_ENV ~= '1'
  then
    return false
  end
  for _, ui in ipairs(vim.api.nvim_list_uis()) do
    if ui.stdout_tty then
      return true
    end
  end
  return false
end

---@param content string
---@return nil
local function send(content)
  if vim.env.TMUX then
    content = esc .. 'Ptmux;' .. content:gsub(esc, esc .. esc) .. terminator
  end
  vim.api.nvim_ui_send(content)
end

---Synchronize Ghostty's default colors and ANSI palette.
---@param palette my.appearance.ghostty.palette
---@param transparent? boolean Preserve the host backdrop when transparent
---@return boolean
function M.sync(palette, transparent)
  if not M.available() then
    return false
  end
  local sequences = {
    osc(10, palette.foreground),
    -- Multiplexers paint an overridden default background as opaque RGB.
    -- Reset it when transparent so SGR 49 reveals the host's own backdrop.
    transparent and osc(111) or osc(11, palette.background),
    osc(12, palette.cursor),
  }
  for i, value in ipairs(palette.colors) do
    sequences[#sequences + 1] = osc(4, (i - 1) .. ';' .. value)
  end
  send(table.concat(sequences))
  changed = true
  return true
end

---Return changed colors to Ghostty's configured defaults.
---@return nil
function M.reset()
  if changed and M.available() then
    local indices = {} ---@type string[]
    for i = 0, 15 do
      indices[#indices + 1] = tostring(i)
    end
    send(
      osc(104, table.concat(indices, ';')) .. osc(110) .. osc(111) .. osc(112)
    )
  end
  changed = false
end

---Export a Ghostty configuration fragment without changing opacity.
---@param path string
---@param palette my.appearance.ghostty.palette
---@return boolean
function M.export(path, palette)
  return require('my.utils.fs').write_file(path, M.compose(palette))
end

---Build a Ghostty theme fragment without changing opacity.
---@param palette my.appearance.ghostty.palette
---@return string
function M.compose(palette)
  local lines = {
    '# Generated by Avra.nvim; regenerate with :Appearance export',
    'background = ' .. palette.background,
    'foreground = ' .. palette.foreground,
    'cursor-color = ' .. palette.cursor,
    'selection-foreground = ' .. palette.selection_foreground,
    'selection-background = ' .. palette.selection_background,
  }
  for i, value in ipairs(palette.colors) do
    lines[#lines + 1] = 'palette = ' .. (i - 1) .. '=' .. value
  end
  return table.concat(lines, '\n') .. '\n'
end

return M
